### ISSUE TITLE
Fan stuck at max speed when sleeping

### ISSUE THREAD

**Issue by james10424** [mayankk2308/purge-wrangler#133]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: iMac 21.5-inch, 2019
- **macOS Version**: 10.14.6
- **System GPUs**: Radeon Pro 560X
- **eGPU**: AROUS Gaming Box + R9 Fury Nano
- **Script Version**: 6.3.3
- **Script Logs**: Attach logs generated by the script.
[pwlog-2021-01-20-17-37-32.zip](https://github.com/mayankk2308/purge-wrangler/files/5845707/pwlog-2021-01-20-17-37-32.zip)

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

### Issue Description
Describe your problem. Does it occur every time?
The GPU fan would go full blast right after sleeping, at random.
If it's on full, it will stay like that until I wake the computer up. Sometimes when I wake the computer up, then sleep immediately, the fan would go full blast again, at random.
I cannot reliably reproduce this bug.

Observations:
It mostly happens when I leave the computer unattended for some time and it automatically sleeps.
Rebooting doesn't fix the issue.
Switching thunderbolt ports doesn't help.
Reinstalling the script doesn't help.

### Expected Behavior
When the computer goes to sleep, the GPU fan should stop spinning because nothing is using it.

**Comment by mayankk2308** [comment]
I have on rare occasion noticed this bug with my R9 Fury (non-Nano), which is really the same GPU. Unfortunately, I am not aware of a solution. It seems like a driver issue since these GPU drivers were never expected to be used in eGPU configuration. Some workarounds to try would be to just manually lock the screen (CMD + CTRL + ESC) and then let display auto-sleep. Have to close the issue as there is nothing much I can do for you, but feel free to reach out here in case you discover something new or have an update.
