### ISSUE TITLE
Unable to patch for TB1/2 AMD eGPUs.

### ISSUE THREAD

**Issue by zippytiff** [mayankk2308/purge-wrangler#134]
last messages on screen

Plug-in eGPU. Press ESC if you are not plugging in eGPU.

External GPU	Radeon RX 470/480/570/570X/580/580X/590
GPU Arch	Ellesmere 
Thunderbolt	1

Backing up...
Backup refreshed.

Patching for AMD eGPUs...
Unable to patch for TB1/2 AMD eGPUs.
Generating system log...
Log generated on the Desktop.

Open an issue on Github and share this file.

[pwlog-2021-03-08-21-40-33.zip](https://github.com/mayankk2308/purge-wrangler/files/6118303/pwlog-2021-03-08-21-40-33.zip)
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro 2011
- **macOS Version**: 10.15.2
- **System GPUs**: Intel 3000
- **eGPU**: Razor Core X with RX580
- **Script Version**: latest (yesterday)
- **Script Logs**: Attach logs generated by the script. YES

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

### Issue Description
Describe your problem. Does it occur every time?

**Comment by Pigami28** [comment]
I've tried patching 2x 2011 mac minis with a GTX 1070 and I applied the script successfully but they would just hang on end of boot all the time. So I gave up, concluding 2011 machines were incompatible with PW because I did succeed on 4x 2012 iMacs with AMD and Nvidia cards.

**Comment by mayankk2308** [comment]
As written here: https://github.com/mayankk2308/purge-wrangler/wiki/Beginner's-Guide#preparations

2011 macs do not natively support Catalina. Using this script alongside dosdude patches does not work.

**Comment by Pigami28** [comment]
Zippytiff, you should install High Sierra 10.3.6 and try again.

**Comment by mayankk2308** [comment]
@Pigami28 hmm, not sure what the cause may be for the hang in your case. Is it hanging with egpu plugged in or just as soon as you plug one in? More context would be great. I’m assuming you’re using High Sierra (since you’re trying with a 1070).

**Comment by Pigami28** [comment]
Yes High Sierra.

I never understood why it didn't work with 2 different 2011 Mac minis because I succeeded 4 times with 2012 iMac/High Sierra before so I was well used to the procedure...
Doesn’t matter anymore, I sold the minis to replace them with the iMacs and they run fine with Radeons and GTXs.

I’m #1 here (Pierre Poulin).  :   https://einsteinathome.org/fr/community/teams/172554/members?order=expavg_credit&sort=desc&amp%3Bsort=desc <https://einsteinathome.org/fr/community/teams/172554/members?order=expavg_credit&sort=desc&amp;sort=desc>

Thank you for a great script !




Le 10 mars 2021 à 14:32, Mayank Kumar <notifications@github.com> a écrit :


@Pigami28 <https://github.com/Pigami28> hmm, not sure what the cause may be for the hang in your case. Is it hanging with egpu plugged in or just as soon as you plug one in? More context would be great. I’m assuming you’re using High Sierra (since you’re trying with a 1070).

**Comment by zippytiff** [comment]
Thx everybody !

ZT

On 10 Mar 2021, at 19:38, Pigami28 ***@***.***> wrote:

﻿

Yes High Sierra.

I never understood why it didn't work with 2 different 2011 Mac minis because I succeeded 4 times with 2012 iMac/High Sierra before so I was well used to the procedure...
Doesn’t matter anymore, I sold the minis to replace them with the iMacs and they run fine with Radeons and GTXs.

I’m #1 here (Pierre Poulin). : https://einsteinathome.org/fr/community/teams/172554/members?order=expavg_credit&sort=desc&amp%3Bsort=desc <https://einsteinathome.org/fr/community/teams/172554/members?order=expavg_credit&sort=desc&amp;sort=desc>

Thank you for a great script !




Le 10 mars 2021 à 14:32, Mayank Kumar ***@***.***> a écrit :


@Pigami28 <https://github.com/Pigami28> hmm, not sure what the cause may be for the hang in your case. Is it hanging with egpu plugged in or just as soon as you plug one in? More context would be great. I’m assuming you’re using High Sierra (since you’re trying with a 1070).
