### ISSUE TITLE
What is the state of System Integrity after install

### ISSUE THREAD

**Issue by MattyBalaam** [mayankk2308/purge-wrangler#2]
Firstly, thank you so much to everyone involved in making this happen, finally having this plug'n'play is magical. I do have one query.

It’s not clear if it is possible to reenable after installing, or if this happens automatically anyway.

**Comment by learex** [comment]
AFAIK, the changed kexts will look unsigned. Therefore SIP should stay disabled. (Curious: does `csrutil enable --without kext` work?)

**Comment by mayankk2308** [comment]
Will test and provide an update very soon.

**Comment by mayankk2308** [comment]
@MattyBalaam Script does not affect SIP status, only checks it. Re-enabling should be ok, but not recommended because you will have to disable it again to patch the next macOS update.

@learex Without kext enabled SIP works fine. Updating SIP checks in script.

**Comment by learex** [comment]
How? Is there no check that the signature fails?

**Comment by mayankk2308** [comment]
Just tested again:

- Ran script with kext signing disabled.
- Completely cleared SIP (fully enabled).
- System functional.

@learex this works similar to automate-eGPU.sh - you can re-enable SIP after applying it. Why it works (complete conjecture) - SIP wants kext to stay unmodified. So when enabled, we can't mod kexts. But once disabled, you can mod it. Then when you re-enable SIP, SIP still wants kext to stay unmodified, but cannot detect any changes since it "wasn't looking when you did it" ;)

**Comment by mayankk2308** [comment]
Note that to recover, SIP will have to be disabled again of course.

**Comment by learex** [comment]
Ahh, for the enabler this doesn't work...
But good to know...

**Comment by mayankk2308** [comment]
Yes, looks like optimal config is **csrutil enabled without kext**. Closing this.
