### ISSUE TITLE
Case-sensitive Filesystem compatibility?

### ISSUE THREAD

**Issue by Espionage724** [mayankk2308/purge-wrangler#35]
I recently did a Catalina install with APFS (Case-sensitive). When I first tried to install purge-wrangler, I noticed the GPU detection didn't detect the full Arch of my GPU (Elsemere or something with like RX 460/480/580), and instead just said `AMD`. During the Sanitize System phase, my MacBook shut off and restarted, along with reporting that there was an issue.

During the next reboot however, my eGPU worked (had display output). Trying to run `purge-wrangler` from Terminal didn't work though (guessing it isn't adding it to PATH?). Trying to reinstall via the script said system was already modified, and to uninstall it first. Uninstalling it and rebooting worked fine.

Reinstalling purge-wrangler after that worked fine though (no reboot at Sanitize step). External monitor output was fine after reboot, but `purge-wrangler` still can't be called from Terminal.

The only difference I made with this install was seemingly using a Case-sensitive filesystem (normally I do insensitive).

- MacBook Pro (Retina, 13-inch, Mid 2014) (TB2)
- macOS Catalina 10.15 (19A602) (zsh shell)
- AKiTiO Thunder2 enclosure (not Ti82)
- Radeon RX 580
- `purge-wrangler.sh` from master at https://github.com/mayankk2308/purge-wrangler/commit/acc22a4dd619eafedd0865c8f8f937d75b412e5d

**Comment by mayankk2308** [comment]
Thank you for the report. From the FAQ:
> **Script recognizes my GPU as a generic AMD or NVIDIA device. Is that ok?**
>
> The script uses an online repository to retrieve the GPU device name for the connected eGPU. In case internet is absent, a generic vendor name (AMD or NVIDIA) is shown instead. This does not affect the necessary logic that determines the required patches. However, in case of NVIDIA GPUs and legacy AMD GPUs, internet will be required in case driver downloads are necessary.

The script places itself into /usr/local/bin/. Could you verify that it is present there?

**Comment by Espionage724** [comment]
I did a macOS reinstall; interestingly the GPU name showed up when I ran the script that time. I kept the case-sensitive filesystem, reinstalled purge-wrangler, and it installed fine (no reboot). Not sure what happened the first time.

I have nothing in `/usr/local/bin`, and `purge-wrangler` still can't be executed after install.

**Comment by mayankk2308** [comment]
@Espionage724 Thank you for checking. I would have expected a copy of the script to be present at `/usr/local/bin/`. Seems like the script is having an issue moving in there on your system. I will examine the logic responsible for handling this and test on a case-sensitive system. Hopefully I can address this in the upcoming v6.0.3 update.

**Comment by mayankk2308** [comment]
@Espionage724 I believe I have figured out the issue. Since you are using the script at `master`, you presumably downloaded it manually - lets say in the `~/Downloads` folder. Running the downloaded script as follows:
```bash
bash ~/Downloads/purge-wrangler.sh
```
Successfully generates `/usr/local/bin` path if absent, but fails to copy the script. However, running as:
```bash
cd ~/Downloads
bash purge-wrangler.sh
```
Seems to work as expected, leaving a copy behind. I will attempt to address this issue in next release.

I do not recommend using the `master` scripts unless expressly for testing or development purposes (which I appreciate of course). The developer document is [here](https://github.com/mayankk2308/purge-wrangler/blob/master/DOCS.md).

In this scenario, there is basically no difference between `6.0.2` and `master`, so I recommend using the README instructions for installation. I tested the README command on a case-sensitive install and all was OK.

**Comment by Espionage724** [comment]
Thanks for the info; basically the problem seems to have been me just running it incorrectly :p

Can confirm that running it like the README states (`cd` to directory the script is in and execute it with `bash`) installs the patches fine, copies `purge-wrangler` to `/usr/local/bin`, executes fine in Terminal afterwards, and works fine on case-sensitive APFS.
