### ISSUE TITLE
Can't login!...

### ISSUE THREAD

**Issue by degrawtech** [mayankk2308/purge-wrangler#84]
![Screen Sharing Picture June 28, 2020 at 5 10 00 PM EDT](https://user-images.githubusercontent.com/25493098/85958328-c5854300-b962-11ea-998f-17471a954611.png)
[pwlog-2020-06-28-17-01-37.zip](https://github.com/mayankk2308/purge-wrangler/files/4843008/pwlog-2020-06-28-17-01-37.zip)

### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: Mac Mini Late-2014
- **macOS Version**: 10.15.5
- **System GPUs**: Intel Iris & NVIDIA GT 750M, etc.
- **eGPU**: Sonnet Breakaway 350 + Radeon RX 470
- **Script Version**: 6.2.5
- **Script Logs**: (see attached)

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

### Issue Description
After updating macOS followed by purge-wrangler, I reinstalled the patch.  After doing so, the computer only boots as far as the login window without listing users, thus preventing login.  This issues persists with the patch both installed and uninstalled.  Furthermore, a reinstallation of macOS also failed to remedy the issue.

### Screenshots
![Screen Sharing Picture June 28, 2020 at 5 10 00 PM EDT](https://user-images.githubusercontent.com/25493098/85958260-498afb00-b962-11ea-9965-3ab4d4c65f59.png)

**Comment by mayankk2308** [comment]
@degrawtech Did you try the recovery steps in the beginner's guide?

**Comment by degrawtech** [comment]
No; I can’t complete that procedure as that the last 20 snapshots listed were created over the last couple of days, after the problem occurred.

**Comment by mayankk2308** [comment]
Try the other link in my message...

**Comment by mayankk2308** [comment]
Any status updates?

**Comment by degrawtech** [comment]
> Any status updates?

The procedure in that second link looks promising. I, however, am still working through it.

**Comment by mayankk2308** [comment]
@degrawtech roger that. Pls let me know how it goes.

**Comment by degrawtech** [comment]
> @degrawtech roger that. Pls let me know how it goes.

Okay, so, that procedure does allow me to ultimately get into the user accounts. But, it doesn't resolve the issue of the broken login window.

**Comment by mayankk2308** [comment]
It is likely that there is an issue with your user account. Consider restoring from a Time Machine backup. The script does not modify any files or permissions inside a specific User directory, and always uses **/Library/Application Support/Purge-Wrangler** directory for writing backups and additional support files. This is most likely an isolated issue with a different root cause that may have coincided with you running the script and rebooting your system. One of the causes can be modifying advanced settings for the user account in System Preferences (which this script does not do).
